name: Code-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore code checker caches
        id: restore-code-checker-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .pyre
            .ruff_cache
            ~/.cache
          key: ${{ runner.os }}-code-checker-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-code-checker

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run Black
        run: hatch run format-check

      - name: Run Ruff
        run: hatch run lint

      - name: Run Pyre
        run: hatch run type-check

      - name: Save code checker caches
        id: save-code-checker-cache
        uses: actions/cache/save@v3
        with:
          path: |
            .pyre
            .ruff_cache
            ~/.cache
          key: ${{ steps.restore-code-checker-cache.outputs.cache-primary-key }}
